export const hotelTypes = [
  "Hotels",
  "Apartments",
  "Villas",
  "Holiday homes",
  "Bed and breakfasts",
  "Homestays",
  "Guest houses",
  "Resorts",
  "Chalets",
  "Hostels",
  "Campsites",
  "Lodges",
  "Boats",
  "Country houses",
  "Holiday parks",
  "Luxury tents",
  "Farm stays",
  "Motels",
  "Capsule hotels",
  "Love hotels",
  "Riads",
  "Cruises",
];

export const hotelFacilities = [
  "Parking",
  "Free WiFi",
  "Restaurant",
  "Pets allowed",
  "Room service",
  "24-hour front desk",
  "Fitness centre",
  "Non-Smoking Rooms",
  "Airport shuttle",
  "Facilities for disabled guests",
  "Family rooms",
  "Spa and wellness centre",
  "Electric vehicle charging station",
  "Swimming pool",
];

export const trendingCities = [
  "London 🇬🇧",
  "Berlin 🇩🇪",
  "Amsterdam 🇳🇱" ,
  "Rome 🇮🇹", 
  "Prague 🇨🇿",
];

export const PopularTypes = [
    "Hotels",
    "Apartments",
    "Villas",
    "Holiday homes",
    "Homestays",
    "Guest houses",
    "Resorts",
    "Chalets",
    "Hostels",
    "Campsites",
    "Lodges",
    "Boats",
    "Country houses",
    "Luxury tents",
    "Farm stays",
    "Motels",
    "Capsule hotels",
    "Love hotels",
    "Riads",
    "Cruises",
  ];